# Generated by Django 5.0.4 on 2024-04-30 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='participants',
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user.svg', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file_type', models.PositiveSmallIntegerField(choices=[(1, 'audio'), (2, 'video'), (3, 'pdf'), (4, 'image')])),
                ('file', models.FileField(upload_to='media/files/%Y/%m/%d/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='base.post')),
            ],
        ),
    ]
