# Generated by Django 5.0.4 on 2024-05-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
