# Generated by Django 5.0.4 on 2024-05-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='documents',
            field=models.ManyToManyField(related_name='files', to='base.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
